2020-08-19 09:40:10.036351 [100238] Child process with pid: 100248 was killed by signal: 15, core dump: 0
2020-08-19 09:40:10.808796 [100238] Child process with pid: 100303 was killed by signal: 15, core dump: 0
2020-08-19 09:42:25.890328 [100238] Child process with pid: 108368 was killed by signal: 15, core dump: 0
2020-08-19 09:42:26.575359 [100238] Child process with pid: 108396 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SaD.wsgi import application
ModuleNotFoundError: No module named 'SaD'
2020-08-19 09:50:40.028715 [7379] Child process with pid: 7388 was killed by signal: 15, core dump: 0
2020-08-19 09:50:40.855142 [7379] Child process with pid: 7439 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SaD.wsgi import application
ModuleNotFoundError: No module named 'SaD'
2020-08-19 09:54:09.036728 [19599] Child process with pid: 19637 was killed by signal: 15, core dump: 0
2020-08-19 09:54:09.768581 [19599] Child process with pid: 19683 was killed by signal: 15, core dump: 0
2020-08-19 09:55:27.447902 [19599] Child process with pid: 24051 was killed by signal: 15, core dump: 0
2020-08-19 09:55:28.153273 [19599] Child process with pid: 24102 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SaD.wsgi import application
ModuleNotFoundError: No module named 'SaD'
Invalid HTTP_HOST header: 'mulvice.org'. You may need to add 'mulvice.org' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'mulvice.org'. You may need to add 'mulvice.org' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'mulvice.org'. You may need to add 'mulvice.org' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'mulvice.org'. You may need to add 'mulvice.org' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'mulvice.org'. You may need to add 'mulvice.org' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'mulvice.org'. You may need to add 'mulvice.org' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'mulvic34_db_SaD.auth_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 410, in login
    return LoginView.as_view(**defaults)(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/forms/forms.py", line 375, in full_clean
    self._clean_form()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/forms/forms.py", line 402, in _clean_form
    cleaned_data = self.clean()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 215, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'mulvic34_db_SaD.auth_user' doesn't exist")
Not Found: /favicon.ico
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<QuerySet []>
<QuerySet []>
<QuerySet []>
2020-08-19 11:01:25.740104 [128585] Child process with pid: 128607 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'SD.settings'
<QuerySet []>
2020-08-19 11:01:26.996809 [128640] Child process with pid: 128661 was killed by signal: 15, core dump: 0
2020-08-19 11:01:31.200875 [128640] Child process with pid: 128865 was killed by signal: 15, core dump: 0
2020-08-19 11:01:48.101037 [128640] Child process with pid: 129736 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'SD.settings'
2020-08-19 11:01:56.248515 [130241] Child process with pid: 130262 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'SD.settings'
2020-08-19 11:02:23.215673 [1151] Child process with pid: 1170 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'SD.settings'
2020-08-19 11:02:39.140514 [1941] Child process with pid: 1968 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'SD.settings'
2020-08-19 11:30:04.247547 [101157] Child process with pid: 101251 was killed by signal: 15, core dump: 0
2020-08-19 11:30:19.784977 [101157] Child process with pid: 102255 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 196, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2020-08-19 12:18:41.141083 [16503] Child process with pid: 16520 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 196, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2020-08-19 13:36:41.191349 [36971] Child process with pid: 36993 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 196, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2020-08-19 14:02:21.459574 [129573] Child process with pid: 129595 was killed by signal: 15, core dump: 0
2020-08-19 14:02:22.132261 [129573] Child process with pid: 129637 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/mulvic34/SaD/passenger_wsgi.py", line 1, in <module>
    from SD.wsgi import application
  File "/home/mulvic34/SaD/SD/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 196, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
<QuerySet []>
Not Found: /favicon.ico
<QuerySet []>
<QuerySet []>
<QuerySet []>
2020-08-19 13:37:19.058259 [125530] Child process with pid: 127098 was killed by signal: 15, core dump: 0
<QuerySet []>
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
2020-08-19 13:44:14.050262 [22472] Child process with pid: 22522 was killed by signal: 15, core dump: 0
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
<QuerySet []>
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<class 'Stock.models.Produit'>
<QuerySet []>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:152: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Sortie'> QuerySet.
  paginator = Paginator(sorties, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:152: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Sortie'> QuerySet.
  paginator = Paginator(sorties, 1) # Show 25 contacts per page.
Not Found: /robots.txt
Not Found: /accounts/login/
Not Found: /services/contact-us/
Not Found: /favicon.ico
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
Not Found: /favicon.ico
Not Found: /accounts/devenir-prestataire/
Not Found: /favicon.ico
Not Found: /services/
Not Found: /favicon.ico
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<QuerySet []>
Short Bleu crosshatch
Not Found: /favicon.ico
Short Bleu crosshatch
Short Bleu crosshatch
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /.well-known/assetlinks.json
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /humans.txt
Not Found: /ads.txt
<QuerySet []>
Not Found: /phpminiadmin.php
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /database/print.css
Not Found: /pma/print.css
Not Found: /phpmyadmin/print.css
Not Found: /myadmin/print.css
Not Found: /phpMyAdmin/print.css
Not Found: /mysql/print.css
Not Found: /services/
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /humans.txt
Not Found: /ads.txt
Not Found: /.env
Not Found: /admin/.env
Not Found: /laravel/.env
Not Found: /public/.env
Not Found: /v1/.env
Not Found: /app/.env
Not Found: /config/.env
Not Found: /core/.env
Not Found: /apps/.env
Not Found: /lib/.env
Not Found: /cron/.env
Not Found: /database/.env
Not Found: /uploads/.env
Not Found: /site/.env
Not Found: /web/.env
Not Found: /administrator/.env
Not Found: /test/wp-login.php
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /blog/wp-login.php
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /humans.txt
Not Found: /ads.txt
Internal Server Error: /
Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'mulvic34_db_SaD.Stock_achat' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mulvic34/SaD/SD/views.py", line 16, in home
    print(nb_achat)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 263, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'mulvic34_db_SaD.Stock_achat' doesn't exist")
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<QuerySet []>
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
<QuerySet []>
Not Found: /robots.txt
Internal Server Error: /
Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 165, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 288, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 545, in resolve
    for pattern in self.url_patterns:
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mulvic34/SaD/SD/urls.py", line 18, in <module>
    from .views import home
  File "/home/mulvic34/SaD/SD/views.py", line 51
    return render(request , template_name , args)
                                                ^
TabError: inconsistent use of tabs and spaces in indentation
Internal Server Error: /
Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mulvic34/SaD/SD/views.py", line 43, in home
    caiss = caiss + e.prix_u * e.qte
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mulvic34/SaD/SD/views.py", line 43, in home
    if e.qte:
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 165, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 288, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 545, in resolve
    for pattern in self.url_patterns:
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/mulvic34/virtualenv/SaD/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mulvic34/SaD/SD/urls.py", line 18, in <module>
    from .views import home
  File "/home/mulvic34/SaD/SD/views.py", line 43
    if e.qte not None:
                    ^
SyntaxError: invalid syntax
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
<class 'Stock.models.Produit'>
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<class 'Stock.models.Produit'>
/home/mulvic34/SaD/Stock/views.py:17: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Produit'> QuerySet.
  paginator = Paginator(produits, 1) # Show 25 contacts per page.
<class 'Stock.models.Produit'>
<class 'Stock.models.Produit'>
Not Found: /favicon.ico
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
/home/mulvic34/SaD/Stock/views.py:174: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Stock.models.Vente'> QuerySet.
  paginator = Paginator(ventes, 1) # Show 25 contacts per page.
Not Found: /favicon.ico
